#!/bin/bash

set -euo pipefail

kubectl get po mp-hello -o jsonpath='{.spec.containers[*].image}' | grep -w kubectl | grep -w nginx | grep -w 'consul'
kubectl exec mp-hello -c shell -- sh -c 'ps | grep sleep'